services:
  traefik:
    image: traefik:v2.3
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      - '--entrypoints.web.http.redirections.entryPoint.to=websecure'
      - '--entrypoints.web.http.redirections.entryPoint.scheme=https'
      - '--entrypoints.web.http.redirections.entrypoint.permanent=true'
      - '--certificatesresolvers.myresolver.acme.tlschallenge=true'
      - '--certificatesresolvers.myresolver.acme.email=${LETSENCRYPT_EMAIL}'
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - ./data/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      default:
        ipv4_address: 172.20.0.10 # Fix Traefik IP to be able to map it on the backend

  fuseki:
    image: semapps/jena-fuseki-webacl
    volumes:
      - ./data/fuseki:/fuseki
    ports:
      - '3030:3030'
    expose:
      - '3030'
    environment:
      ADMIN_PASSWORD: ${FUSEKI_PASSWORD}

  activitypods-backend:
    image: activitypods/backend
    depends_on:
      - fuseki
      - redis
    volumes:
      - ./data/backend/logs:/app/backend/logs
      - ./data/backend/jwt:/app/backend/jwt
      - ./data/backend/uploads:/app/backend/uploads
      - ./data/fuseki:/fuseki-data # Needed to allow the backend to access Fuseki data
    expose:
      - '3000'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.backend.rule=Host(`${BACKEND_DOMAIN_NAME}`)'
      - 'traefik.http.routers.backend.entrypoints=websecure'
      - 'traefik.http.routers.backend.tls.certresolver=myresolver'
    env_file:
      - .env.backend
      - path: .env.backend.local
        required: false
    # Redirect backend calls to Traefik container
    # Required to allow the backend to "fetch itself"
    extra_hosts:
      - "${BACKEND_DOMAIN_NAME}:172.20.0.10"

  activitypods-frontend:
    image: activitypods/frontend
    depends_on:
      - activitypods-backend
    restart: always
    expose:
      - '5000'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.frontend.rule=Host(`${FRONTEND_DOMAIN_NAME}`)'
      - 'traefik.http.routers.frontend.entrypoints=websecure'
      - 'traefik.http.routers.frontend.tls.certresolver=myresolver'
    environment:
      REACT_APP_CONFIG_URL: 'https://${BACKEND_DOMAIN_NAME}/.well-known/config.js'

  redis:
    image: redis
    container_name: redis
    expose:
      - '6379'
    volumes:
      - ./data/redis:/data:z
    command: ['redis-server', '--appendonly', 'yes']

  arena:
    image: activitypods/arena
    restart: always
    volumes:
      - ./arena.json:/opt/arena/src/server/config/index.json
    depends_on:
      - redis
    ports:
      - '4567:4567'
    expose:
      - '4567'
    environment:
      REDIS_HOST: 'redis'

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16
