services:
  traefik:
    image: traefik:v2.3
    command:
      - '--api.insecure=true'
      - '--metrics'
      - '--metrics.prometheus=true'
      - '--metrics.prometheus.buckets=0.1,0.3,1.2,5.0'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      - '--entrypoints.web.http.redirections.entryPoint.to=websecure'
      - '--entrypoints.web.http.redirections.entryPoint.scheme=https'
      - '--entrypoints.web.http.redirections.entrypoint.permanent=true'
      - '--certificatesresolvers.myresolver.acme.tlschallenge=true'
      - '--certificatesresolvers.myresolver.acme.email=${LETSENCRYPT_EMAIL}'
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - ./data/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      default:
        aliases:
          - $BACKEND_DOMAIN_NAME

  fuseki:
    image: semapps/jena-fuseki-webacl
    volumes:
      - ./data/fuseki:/fuseki
    ports:
      - '3030:3030'
    expose:
      - '3030'
    environment:
      ADMIN_PASSWORD: ${FUSEKI_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:3030 || exit 1
      interval: 1s
      timeout: 1s

  activitypods-backend:
    image: activitypods/backend
    depends_on:
      - fuseki
      - redis
    volumes:
      - ./data/backend/actors:/app/backend/actors
      - ./data/backend/logs:/app/backend/logs
      - ./data/backend/jwt:/app/backend/jwt
      - ./data/backend/uploads:/app/backend/uploads
      - ./data/fuseki:/fuseki-data # Needed to allow the backend to access Fuseki data
    expose:
      - '3000'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.backend.rule=Host(`${BACKEND_DOMAIN_NAME}`)'
      - 'traefik.http.routers.backend.entrypoints=websecure'
      - 'traefik.http.routers.backend.tls.certresolver=myresolver'
    env_file:
      - .env.backend
      - path: .env.backend.local
        required: false

  activitypods-frontend:
    image: activitypods/frontend
    depends_on:
      - activitypods-backend
    restart: always
    expose:
      - '5000'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.frontend.rule=Host(`${FRONTEND_DOMAIN_NAME}`)'
      - 'traefik.http.routers.frontend.entrypoints=websecure'
      - 'traefik.http.routers.frontend.tls.certresolver=myresolver'
    environment:
      REACT_APP_CONFIG_URL: 'https://${BACKEND_DOMAIN_NAME}/.well-known/config.js'

  redis:
    image: redis
    expose:
      - '6379'
    volumes:
      - ./data/redis:/data:z
    command: [ 'redis-server', '--appendonly', 'yes' ]
    networks:
      default:
        ipv4_address: 172.20.5.11 # Fix Redis IP to make it easier to find it with a GUI

  arena:
    image: activitypods/arena
    restart: always
    volumes:
      - ./arena.json:/opt/arena/src/server/config/index.json
    depends_on:
      - redis
    ports:
      - '4567:4567'
    expose:
      - '4567'
    environment:
      REDIS_HOST: 'redis'

  tripleadmin:
    image: mguihal/tripleadmin
    depends_on:
      - fuseki
    ports:
      - '3033:3033'
    extra_hosts:
      - 'localhost:host-gateway'

  # For Promotheus monitoring
  # See https://github.com/prometheus/node_exporter?tab=readme-ov-file#docker
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    restart: unless-stopped
    command:
      - '--path.rootfs=/host'
    pid: host
    volumes:
      - '/:/host:ro,rslave'
    network_mode: host

  # For Promotheus monitoring
  # See https://prometheus.io/docs/guides/cadvisor/
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - 8090:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.20.5.0/24
          gateway: 172.20.5.254
